include: package:lints/recommended.yaml

analyzer:
  errors:
    unused_import: warning

linter:
  rules:
    prefer_conditional_assignment: false # annoying for no reason
    unnecessary_brace_in_string_interps: false # annoying for no reason
    prefer_interpolation_to_compose_strings: false # annoying for no reason
    avoid_function_literals_in_foreach_calls: false # i like forEach
