name: dart_types
description: A simple package for constructing type lattice and its presentation from Dart code
version: 0.0.1
repository: https://github.com/osaxma/dart_types

environment:
  sdk: ^3.2.3

dependencies:
  analyzer: ^6.4.0
  args: ^2.4.2
  collection: ^1.18.0
  path: ^1.9.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
