name: dart_types
description: A utility cli and package to construct and present the type graph of Dart type(s).
version: 0.0.3+1
repository: https://github.com/osaxma/dart_types

executables:
  dart_types: dart_types

environment:
  sdk: ^3.2.3

dependencies:
  analyzer: ^6.4.0
  args: ^2.4.2
  cli_util: ^0.4.1
  collection: ^1.18.0
  path: ^1.9.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
